import didi_b from './assets/didi_b_ivoire.jpg'
import booba1 from './assets/booba1.jpg'
import blackM from './assets/black_m_fr.jpg'
import lefa from './assets/lefa_fr.jpg'
import magiSytem from './assets/magic_systeme.jpg'

export const productsData = [
    {
        id: 1,
        image : didi_b,
        title: "DIDI B en concert live",
        price: 140,
        genre_musical:'Coupé decalé',
        category: 'VVIP',
        date:'14/05/2025',
        description: 'Préparez-vous pour une soirée inoubliable !, phénomène de la scène, vous donne rendez-vous pour un concert unique. Venez vibrer au rythme de ses plus grands hits et découvrir en live les titres de son dernier album.',
    },
    {
        id: 2,
        image: booba1,
        title: "New concert Booba",
        price: 140,
        genre_musical:'RAP',
        category: 'VVIP',
        date:'14/05/2025',
        description: 'Préparez-vous pour une soirée inoubliable !, phénomène de la scène, vous donne rendez-vous pour un concert unique. Venez vibrer au rythme de ses plus grands hits et découvrir en live les titres de son dernier album.',
    },
    {
        id: 3,
        image : blackM,
        title: "Le king du rap Black en live",
        price: 140,
        genre_musical:'RAP',
        category: 'VVIP',
        date:'14/05/2025',
        description: 'Préparez-vous pour une soirée inoubliable !, phénomène de la scène, vous donne rendez-vous pour un concert unique. Venez vibrer au rythme de ses plus grands hits et découvrir en live les titres de son dernier album.',
    },
    {
        id: 4,
        image : magiSytem,
        title: "Le groupe en live show",
        price: 140,
        genre_musical:'ZOUGLOU',
        category: 'VVIP',
        date:'14/05/2025',
        description: 'Préparez-vous pour une soirée inoubliable !, phénomène de la scène, vous donne rendez-vous pour un concert unique. Venez vibrer au rythme de ses plus grands hits et découvrir en live les titres de son dernier album.',
    },
    {
        id: 5,
        image : lefa,
        title: "Concert live Lefa",
        price: 140,
        genre_musical:'',
        category: 'RAP',
        date:'14/05/2025',
        description: 'Préparez-vous pour une soirée inoubliable !, phénomène de la scène, vous donne rendez-vous pour un concert unique. Venez vibrer au rythme de ses plus grands hits et découvrir en live les titres de son dernier album.',
    },
    {
        id: 6,
        image : didi_b,
        title: "DIDI B en concert live",
        price: 140,
        genre_musical:'Coupé decalé',
        category: 'VVIP',
        date:'14/05/2025',
        description: 'Préparez-vous pour une soirée inoubliable !, phénomène de la scène, vous donne rendez-vous pour un concert unique. Venez vibrer au rythme de ses plus grands hits et découvrir en live les titres de son dernier album.',
    },
    {
        id: 7,
        image: booba1,
        title: "New concert Booba",
        price: 140,
        genre_musical:'RAP',
        category: 'VVIP',
        date:'14/05/2025',
        description: 'Préparez-vous pour une soirée inoubliable !, phénomène de la scène, vous donne rendez-vous pour un concert unique. Venez vibrer au rythme de ses plus grands hits et découvrir en live les titres de son dernier album.',
    },
    {
        id: 8,
        image : blackM,
        title: "Le king du rap Black en live",
        price: 140,
        genre_musical:'RAP',
        category: 'VVIP',
        date:'14/05/2025',
        description: 'Préparez-vous pour une soirée inoubliable !, phénomène de la scène, vous donne rendez-vous pour un concert unique. Venez vibrer au rythme de ses plus grands hits et découvrir en live les titres de son dernier album.',
    },
    {
        id: 9,
        image : magiSytem,
        title: "Le groupe en live show",
        price: 140,
        genre_musical:'ZOUGLOU',
        category: 'VVIP',
        date:'14/05/2025',
        description: 'Préparez-vous pour une soirée inoubliable !, phénomène de la scène, vous donne rendez-vous pour un concert unique. Venez vibrer au rythme de ses plus grands hits et découvrir en live les titres de son dernier album.',
    },
    {
        id: 10,
        image : lefa,
        title: "Concert live Lefa",
        price: 140,
        genre_musical:'RAP',
        category: 'VVIP',
        date:'14/05/2025',
        description: 'Préparez-vous pour une soirée inoubliable !, phénomène de la scène, vous donne rendez-vous pour un concert unique. Venez vibrer au rythme de ses plus grands hits et découvrir en live les titres de son dernier album.',
    }
]